package com.growkaro.backend.entity;

public enum ActivityType {
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,

    SCHEME_ENROLLED,
    SCHEME_REJECTED,
    SCHEME_WITHDRAWAL,

    DEPOSIT_REQUESTED,
    DEPOSIT_COMPLETED,

    WITHDRAWAL_REQUESTED,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED,

    KYC_SUBMITTED,
    KYC_APPROVED,
    KYC_REJECTED,

    REFERRAL_CREATED
}
