import React, { useState } from "react";
import { Mail, Eye, EyeOff, CheckCircle2, X } from "lucide-react";

export function SuccessBanner({ payload, onClose, onSendEmail }) {
  const [showPassword, setShowPassword] = useState(false);

  if (!payload) return null;

  return (
    <div className="bg-slate-900 border-2 border-emerald-500/30 rounded-2xl p-5 transition-all duration-300 space-y-4">
      <div className="flex items-start justify-between">
        <div className="flex items-center gap-3">
          <div className="bg-emerald-500/10 p-2 rounded-xl text-emerald-400">
            <CheckCircle2 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-slate-100">
              Remitter Onboarded Successfully
            </h3>
            <p className="text-xs text-slate-400 mt-0.5">
              Secure gateway credentials generated by authorization server.
            </p>
          </div>
        </div>
        <button
          onClick={onClose}
          className="text-slate-500 hover:text-slate-300 transition-colors"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-slate-950/60 p-4 rounded-xl border border-slate-800/80 text-xs font-mono">
        <div className="space-y-1">
          <span className="text-slate-500 block text-[10px] font-sans uppercase font-bold tracking-wider">
            Login / Portal ID
          </span>
          <span className="text-slate-200 select-all">{payload.loginId}</span>
        </div>
        <div className="space-y-1 relative">
          <span className="text-slate-500 block text-[10px] font-sans uppercase font-bold tracking-wider">
            Temporary Password
          </span>
          <div className="flex items-center justify-between pr-2">
            <span className="text-slate-200 select-all">
              {showPassword ? payload.password : "••••••••"}
            </span>
            <button
              type="button"
              onClick={() => setShowPassword(!showPassword)}
              className="text-slate-400 hover:text-slate-200"
            >
              {showPassword ? (
                <EyeOff className="w-3.5 h-3.5" />
              ) : (
                <Eye className="w-3.5 h-3.5" />
              )}
            </button>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-end">
        <button
          onClick={onSendEmail}
          disabled={payload.emailSent}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold shadow-xs transition-all ${
            payload.emailSent
              ? "bg-slate-800 text-slate-500 cursor-not-allowed border border-slate-700/50"
              : "bg-blue-600 hover:bg-blue-500 text-white active:scale-[0.98]"
          }`}
        >
          <Mail className="w-3.5 h-3.5" />
          {payload.emailSent
            ? "Credentials Dispatched via Email"
            : "Email, Login Details to Remitter"}
        </button>
      </div>
    </div>
  );
}
