package com.growkaro.backend.enums;

public enum ActivityType {
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,

    SCHEME_ENROLLED,
    SCHEME_REJECTED,
    SCHEME_WITHDRAWAL,

    DEPOSIT_REQUESTED,
    DEPOSIT_COMPLETED,

    WITHDRAWAL_REQUESTED,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED,
    WITHDRAWAL_PROCESSED,
    WITHDRAWAL_COMPLETED,

    KYC_SUBMITTED,
    KYC_APPROVED,
    KYC_REJECTED,

    REFERRAL_CREATED,
    REMITTER_ADDED,
    REMITTER_UPDATED,
    REMITTER_DELETED
}
