server:
  port: ${SERVER_PORT:4000}
  shutdown: graceful

  tomcat:
    threads:
      max: 30
      min-spare: 5
    max-connections: 500
    accept-count: 50
    connection-timeout: 20000

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 2048

spring:
  main:
    banner-mode: "off"

  lifecycle:
    timeout-per-shutdown-phase: 20s

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1500000

  jpa:
    hibernate:
      ddl-auto: update  # if changes are made in entity classes, set this to update. For production, consider using 'validate' or 'none'.
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: "OFF"
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN
    com.zaxxer.hikari: WARN

app:
  storage:
    type: local
    local:
      base-path: ${STORAGE_BASE_PATH:/app/uploads}
      base-url: /uploads

frontend:
  url: ${FRONTEND_URL}

admin:
  email: ${ADMIN_EMAIL}